name: Build and Package app

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
    - 'Makapi/**'
    - '.github/workflows/build-package.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'Makapi/**'
    - '.github/workflows/build-package.yml'

jobs:

  build:

    strategy:
      matrix:
        configuration: [ Release ]
        platform: [ x64, x86 ]

    runs-on: windows-latest

    env:
      Solution_Name: Makapi.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Publish application
      run: |
        dotnet publish $env:Solution_Name `
          -c ${{ matrix.configuration }} `
          -r win-${{ matrix.platform }} `
          -p:Platform=${{ matrix.platform }} `
          -p:SelfContained=true `
          -p:WindowsAppSDKSelfContained=true `
          -p:WindowsPackageType=None `
          -p:PublishSingleFile=false `
          -p:PublishTrimmed=false `
          -p:PublishReadyToRun=false `
          -p:PublishProfile= `
          -o bin\win-${{ matrix.platform }}\publish\win-${{ matrix.platform }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v6
      with:
        name: app-${{ matrix.platform }}
        path: bin\win-${{ matrix.platform }}\publish\win-${{ matrix.platform }}\
